<img src="images/HomePage.png" alt="Home Page" width="150" height="30" />
<img src="images/SiteLayout.png" alt="Site Layout" width="150" height="30" />
<img src="images/ControlStructures.png" alt="Control Structures" width="150" height="30" />
<img src="images/StringFunctions.png" alt="String Functions" width="150" height="30" />
<img src="images/WebForms.png" alt="Web Forms" width="150" height="30" />
<img src="images/MidtermAssessment.png" alt="Midterm Assessment" width="150" height="30" />
<img src="images/StateInformation.png" alt="State Information" width="150" height="30" />
<img src="images/UserTemplates.png" alt="User Templates" width="150" height="30" />
<img src="images/FinalProject.png" alt="Final Project" width="150" height="30" />